/**
 * Source photo mapping for the demo inventory.
 * Each car slug maps (in display order) to photo files that are downloaded
 * into `image-search/` or already present in `public/assets/img/`.
 * Run `npm run prepare-images` after changing this file.
 */
export const photoSources = {
  'suzuki-alto-vxr': [
    'assets/img/alto.jpg',
    'image-search/suzuki-alto-vxr-car-pakistan-white-1.webp',
    'image-search/suzuki-alto-vxr-car-pakistan-white-4.webp',
    'image-search/suzuki-alto-vxr-car-pakistan-white-2.webp',
    'image-search/suzuki-alto-vxr-car-pakistan-white-3.webp',
  ],
  'suzuki-alto-vxl-ags': [
    'image-search/suzuki-alto-vxr-car-pakistan-white-5.webp',
    'image-search/suzuki-alto-vxr-car-pakistan-white-3.webp',
    'image-search/suzuki-alto-vxr-car-pakistan-white-1.webp',
    'image-search/suzuki-alto-vxr-car-pakistan-white-4.webp',
  ],
  'suzuki-mehran-vxr': [
    'assets/img/mehran.jpg',
    'image-search/suzuki-mehran-vxr-car-pakistan-1.webp',
    'image-search/suzuki-mehran-vxr-car-pakistan-2.webp',
    'image-search/suzuki-mehran-vxr-car-pakistan-3.webp',
    'image-search/suzuki-mehran-vxr-car-pakistan-4.jpg',
  ],
  'suzuki-cultus-vxl': [
    'image-search/suzuki-cultus-vxl-hatchback-pakistan-1.jpg',
    'image-search/suzuki-cultus-vxl-hatchback-pakistan-2.webp',
    'image-search/suzuki-cultus-vxl-hatchback-pakistan-4.webp',
    'image-search/suzuki-cultus-vxl-hatchback-pakistan-3.webp',
    'image-search/suzuki-cultus-vxl-hatchback-pakistan-5.webp',
  ],
  'suzuki-wagon-r-vxl': [
    'image-search/suzuki-wagon-r-pakistan-car-3.jpg',
    'image-search/suzuki-wagon-r-pakistan-car-1.jpg',
    'image-search/suzuki-wagon-r-pakistan-car-5.jpg',
    'image-search/suzuki-wagon-r-pakistan-car-2.webp',
    'image-search/suzuki-wagon-r-pakistan-car-4.webp',
  ],
  'suzuki-swift-glx': [
    'image-search/suzuki-swift-pakistan-hatchback-3.jpg',
    'image-search/suzuki-swift-pakistan-hatchback-1.jpg',
    'image-search/suzuki-swift-pakistan-hatchback-2.jpg',
    'image-search/suzuki-swift-pakistan-hatchback-4.jpg',
    'image-search/suzuki-swift-pakistan-hatchback-5.jpg',
  ],
  'suzuki-bolan-vx': [
    'image-search/suzuki-bolan-van-pakistan-3.jpg',
    'image-search/suzuki-bolan-van-pakistan-4.jpg',
    'image-search/suzuki-bolan-van-pakistan-1.jpg',
    'image-search/suzuki-bolan-van-pakistan-2.jpg',
    'image-search/suzuki-bolan-van-pakistan-5.webp',
  ],
  'suzuki-ravi': [
    'image-search/suzuki-ravi-pickup-pakistan-1.jpg',
    'image-search/suzuki-ravi-pickup-pakistan-2.jpg',
    'image-search/suzuki-ravi-pickup-pakistan-3.jpg',
    'image-search/suzuki-ravi-pickup-pakistan-4.jpg',
    'image-search/suzuki-ravi-pickup-pakistan-5.png',
  ],
  'toyota-corolla-gli': [
    'assets/img/corolla.jpg',
    'image-search/toyota-corolla-gli-2019-pakistan-sedan-5.jpg',
    'image-search/toyota-corolla-gli-2019-pakistan-sedan-1.jpg',
    'image-search/toyota-corolla-gli-2019-pakistan-sedan-2.jpg',
    'image-search/toyota-corolla-gli-2019-pakistan-sedan-3.jpg',
  ],
  'toyota-corolla-altis': [
    'image-search/toyota-corolla-altis-1-6-pakistan-3.jpg',
    'image-search/toyota-corolla-altis-1-6-pakistan-1.jpg',
    'image-search/toyota-corolla-altis-1-6-pakistan-2.jpg',
    'image-search/toyota-corolla-altis-1-6-pakistan-4.jpg',
    'image-search/toyota-corolla-altis-1-6-pakistan-5.webp',
  ],
  'toyota-yaris-ativ': [
    'assets/img/yaris.jpg',
    'image-search/toyota-yaris-sedan-pakistan-2.jpg',
    'image-search/toyota-yaris-sedan-pakistan-3.jpg',
    'image-search/toyota-yaris-sedan-pakistan-4.jpg',
    'image-search/toyota-yaris-sedan-pakistan-1.webp',
  ],
  'toyota-vitz-hybrid': [
    'image-search/toyota-vitz-hatchback-japan-2.jpg',
    'image-search/toyota-vitz-hatchback-japan-3.jpg',
    'image-search/toyota-vitz-hatchback-japan-5.jpg',
    'image-search/toyota-vitz-hatchback-japan-1.jpg',
    'image-search/toyota-vitz-hatchback-japan-4.jpg',
  ],
  'toyota-passo-x': [
    'image-search/toyota-passo-hatchback-japan-1.jpg',
    'image-search/toyota-passo-hatchback-japan-2.jpg',
    'image-search/toyota-passo-hatchback-japan-3.jpg',
    'image-search/toyota-passo-hatchback-japan-4.jpg',
    'image-search/toyota-passo-hatchback-japan-5.jpg',
  ],
  'toyota-prado-tx': [
    'image-search/toyota-land-cruiser-prado-pakistan-suv-3.jpg',
    'image-search/toyota-land-cruiser-prado-pakistan-suv-1.jpg',
    'image-search/toyota-land-cruiser-prado-pakistan-suv-2.jpg',
    'image-search/toyota-land-cruiser-prado-pakistan-suv-4.jpg',
    'image-search/toyota-land-cruiser-prado-pakistan-suv-5.jpg',
  ],
  'toyota-hilux-revo': [
    'image-search/toyota-hilux-revo-double-cab-pakistan-3.jpg',
    'image-search/toyota-hilux-revo-double-cab-pakistan-4.jpg',
    'image-search/toyota-hilux-revo-double-cab-pakistan-5.jpg',
    'image-search/toyota-hilux-revo-double-cab-pakistan-2.jpg',
    'image-search/toyota-hilux-revo-double-cab-pakistan-1.webp',
  ],
  'toyota-fortuner-legender': [
    'assets/img/suv-premium.jpg',
    'assets/img/suv.jpg',
  ],
  'honda-city-1-2': [
    'image-search/honda-city-sedan-pakistan-4.jpg',
    'image-search/honda-city-sedan-pakistan-5.jpg',
    'image-search/honda-city-sedan-pakistan-1.jpg',
    'image-search/honda-city-sedan-pakistan-2.jpg',
    'image-search/honda-city-sedan-pakistan-3.jpg',
  ],
  'honda-civic-oriel': [
    'image-search/honda-civic-sedan-pakistan-5.jpg',
    'image-search/honda-civic-sedan-pakistan-4.webp',
    'image-search/honda-civic-sedan-pakistan-3.jpg',
    'image-search/honda-civic-sedan-pakistan-1.jpg',
    'image-search/honda-civic-sedan-pakistan-2.jpg',
  ],
  'honda-br-v': [
    'image-search/honda-br-v-7-seater-pakistan-4.webp',
    'image-search/honda-br-v-7-seater-pakistan-2.jpg',
    'image-search/honda-br-v-7-seater-pakistan-5.webp',
    'image-search/honda-br-v-7-seater-pakistan-1.jpg',
    'image-search/honda-br-v-7-seater-pakistan-3.jpg',
  ],
  'honda-vezel-hybrid': [
    'image-search/honda-vezel-hybrid-suv-japan-1.jpg',
    'image-search/honda-vezel-hybrid-suv-japan-4.jpg',
    'image-search/honda-vezel-hybrid-suv-japan-3.jpg',
    'image-search/honda-vezel-hybrid-suv-japan-5.jpg',
    'image-search/honda-vezel-hybrid-suv-japan-2.jpg',
  ],
  'kia-sportage-awd': [
    'image-search/kia-sportage-pakistan-suv-white-2.webp',
    'image-search/kia-sportage-pakistan-suv-white-1.jpg',
    'image-search/kia-sportage-pakistan-suv-white-3.jpg',
    'image-search/kia-sportage-pakistan-suv-white-5.jpg',
    'image-search/kia-sportage-pakistan-suv-white-4.webp',
  ],
  'hyundai-tucson-fwd': [
    'image-search/hyundai-tucson-pakistan-suv-3.jpg',
    'image-search/hyundai-tucson-pakistan-suv-1.jpg',
    'image-search/hyundai-tucson-pakistan-suv-2.webp',
    'image-search/hyundai-tucson-pakistan-suv-4.jpg',
    'image-search/hyundai-tucson-pakistan-suv-5.jpg',
  ],
  'mg-hs-essence': [
    'image-search/mg-hs-suv-pakistan-2.jpg',
    'image-search/mg-hs-suv-pakistan-3.jpg',
    'image-search/mg-hs-suv-pakistan-4.jpg',
    'image-search/mg-hs-suv-pakistan-5.webp',
    'image-search/mg-hs-suv-pakistan-1.jpg',
  ],
  'daihatsu-mira-es': [
    'image-search/daihatsu-mira-hatchback-japan-kei-car-1.png',
    'image-search/daihatsu-mira-hatchback-japan-kei-car-3.jpg',
    'image-search/daihatsu-mira-hatchback-japan-kei-car-4.jpg',
    'image-search/daihatsu-mira-hatchback-japan-kei-car-2.jpg',
  ],
};
