/**
 * Content that seeds a fresh installation (used both for the Supabase seeder and
 * for the offline demo store). Edit here, then run `npm run seed`.
 *
 * Every table that the admin panel can change is represented so nothing is
 * hard-coded in the HTML templates.
 */

export const site = {
  businessNameEn: 'Al Rafay Corporation & Traders',
  businessNameUr: 'الرافع کارپوریشن اینڈ ٹریڈرز',
  shortName: 'Al Rafay',
  logoUrl: '',
  logoAltUrl: '',
  taglineEn: 'New & used cars — bought and sold with confidence in Islamabad',
  taglineUr: 'اسلام آباد میں نئی اور پرانی گاڑیوں کی قابلِ اعتماد خرید و فروخت',
  heroTitleEn: 'Find the car that fits your life',
  heroTitleUr: 'اپنی پسند کی گاڑی، بھروسے کے ساتھ',
  heroSubtitleEn: 'Suzuki, Toyota, Honda, Kia, Hyundai and more — inspected stock, clear pricing and paperwork handled on the spot at Thanda Pani, Lethrar Road, Islamabad.',
  heroSubtitleUr: 'سوزوکی، ٹویوٹا، ہونڈا، کیا، ہنڈائی اور دیگر — مکمل جانچ شدہ گاڑیاں، صاف شفاف قیمت اور موقع پر کاغذات کی سہولت، ٹھنڈا پانی، لتراڑ روڈ، اسلام آباد۔',
  aboutEn: 'Al Rafay Corporation & Traders is a family-run car dealership on Lethrar Road, Islamabad. We buy and sell both new and pre-owned vehicles, help you compare honest options within your budget, and complete the transfer paperwork for you — no hidden charges, no surprises.',
  aboutUr: 'الرافع کارپوریشن اینڈ ٹریڈرز لتراڑ روڈ اسلام آباد پر ایک خاندانی کاروبار ہے۔ ہم نئی اور پرانی دونوں قسم کی گاڑیاں خریدتے اور بیچتے ہیں، آپ کے بجٹ میں سچے آپشنز دکھاتے ہیں اور ٹرانسفر کے تمام کاغذات خود مکمل کرواتے ہیں — کوئی چھپی ہوئی فیس نہیں، کوئی دھوکہ نہیں۔',
  addressEn: 'Thanda Pani (Harno), Lethrar Road, Islamabad, Pakistan',
  addressUr: 'ٹھنڈا پانی (ہرنو)، لتراڑ روڈ، اسلام آباد، پاکستان',
  cityEn: 'Islamabad',
  cityUr: 'اسلام آباد',
  addressShortEn: 'Lethrar Road, Thanda Pani, Islamabad',
  addressShortUr: 'لتراڑ روڈ، ٹھنڈا پانی، اسلام آباد',
  mapEmbedUrl: 'https://www.google.com/maps?q=Thanda+Pani+Lethrar+Road+Islamabad&output=embed',
  mapLink: 'https://www.google.com/maps/search/?api=1&query=Thanda+Pani+Lethrar+Road+Islamabad',
  mapEmbedType: 'src',
  whatsappNumber: '923155521697',
  email: '',
  hoursEn: 'Monday – Saturday: 9:00 am – 8:00 pm',
  hoursUr: 'پیر تا ہفتہ: صبح 9 بجے سے رات 8 بجے تک',
  facebookUrl: '',
  instagramUrl: '',
  youtubeUrl: '',
  footerNoteEn: 'Prices are negotiable and subject to final inspection. Please confirm availability on call before travelling.',
  footerNoteUr: 'قیمتیں قابلِ گفتگو ہیں اور مکمل معائنے سے مشروط ہیں۔ تشریف لانے سے پہلے کال پر دستیابی کی تصدیق کر لیں۔',
  creditsEn: 'Website designed by Abdul Hadi',
  creditsUr: 'ویب سائٹ ڈیزائن: عبدالہادی',
  adminEmail: 'abdulhadicreates@gmail.com',
};

export const owners = [
  {
    nameEn: 'Chaudhry Naeem Akhtar',
    nameUr: 'چوہدری نعیم اختر',
    roleEn: 'Owner & Sales',
    roleUr: 'مالک و سیل',
    phone: '03155521697',
    whatsapp: '923155521697',
    showOnSite: true,
  },
  {
    nameEn: 'Chaudhry Faheem Akhtar',
    nameUr: 'چوہدری فہیم اختر',
    roleEn: 'Owner & Purchasing',
    roleUr: 'مالک و خریداری',
    phone: '03000119297',
    whatsapp: '923000119297',
    showOnSite: true,
  },
];

export const stats = [
  { value: 2000, suffix: '+', labelEn: 'Cars sold', labelUr: 'گاڑیاں فروخت' },
  { value: 20, suffix: '', labelEn: 'Years in business', labelUr: 'سال کا تجربہ' },
  { value: 500, suffix: '+', labelEn: 'Happy customers', labelUr: 'مطمئن گاہک' },
  { value: 100, suffix: '%', labelEn: 'Documentation support', labelUr: 'کاغذات کی معاونت' },
];

export const whyUs = [
  {
    icon: 'shield',
    titleEn: 'Every car is inspected',
    titleUr: 'ہر گاڑی مکمل جانچ شدہ',
    bodyEn: 'Engine, suspension, tyres and body are checked before a car reaches our yard. You are told exactly what has been repaired or replaced.',
    bodyUr: 'گاڑی ہمارے پلاٹ پر آنے سے پہلے انجن، سسپنشن، ٹائر اور باڈی کی مکمل جانچ ہوتی ہے۔ جو پرزہ بدلا یا مرمت ہوا ہو، وہ صاف بتایا جاتا ہے۔',
  },
  {
    icon: 'tag',
    titleEn: 'Transparent pricing',
    titleUr: 'صاف شفاف قیمت',
    bodyEn: 'The price you see is the price we discuss. No hidden fees, no pressure — and a fair offer if you trade in your current car.',
    bodyUr: 'جو قیمت نظر آتی ہے، بات اُسی پر ہوتی ہے۔ کوئی چھپی ہوئی فیس نہیں، کوئی دباؤ نہیں — اور آپ کی پرانی گاڑی کے بدلے مناسب آفر۔',
  },
  {
    icon: 'file',
    titleEn: 'Paperwork we handle for you',
    titleUr: 'کاغذات ہم خود مکمل کریں',
    bodyEn: 'Transfer, registration and token tax guidance is handled by our team so you drive away without chasing offices.',
    bodyUr: 'ٹرانسفر، رجسٹریشن اور ٹوکن ٹیکس کی رہنمائی ہماری ٹیم خود کرتی ہے تاکہ آپ کو دفاتر کے چکر نہ لگانے پڑیں۔',
  },
  {
    icon: 'wrench',
    titleEn: 'After-sale support',
    titleUr: 'فروخت کے بعد بھی سہارا',
    bodyEn: 'Trip before a long journey, an oil change reminder or a spare part — call either owner any time after the sale.',
    bodyUr: 'لمبے سفر سے پہلے چیکنگ، آئل چینج کی یاد دہانی یا اسپیئر پارٹ — فروخت کے بعد بھی کسی بھی وقت ہم سے رابطہ کریں۔',
  },
];

export const faqs = [
  {
    questionEn: 'Can I sell my own car to Al Rafay Corporation?',
    questionUr: 'کیا میں اپنی گاڑی الرافع کارپوریشن کو بیچ سکتا ہوں؟',
    answerEn: 'Yes. Bring the car, its documents and your CNIC to Thanda Pani. We inspect it, quote a fair market price the same day and complete the transfer paperwork if you accept.',
    answerUr: 'جی ہاں۔ گاڑی، کاغذات اور شناختی کارڈ لے کر ٹھنڈا پانی تشریف لائیں۔ ہم گاڑی چیک کر کے اسی دن مناسب قیمت بتاتے ہیں اور آپ کی رضامندی پر تمام کاغذات مکمل کر دیتے ہیں۔',
  },
  {
    questionEn: 'Do you accept a car exchange with a partial payment?',
    questionUr: 'کیا پرانی گاڑی کے بدلے نئی گاڑی اور کچھ رقم کی سہولت ہے؟',
    answerEn: 'Yes, exchange deals are welcome. We value your car in front of you and adjust it against the new one so only the balance is payable.',
    answerUr: 'جی ہاں، ایکسچینج ڈیل دستیاب ہے۔ ہم آپ کے سامنے گاڑی کی ویلیو لگاتے ہیں اور وہ نئی گاڑی کی قیمت میں ایڈجسٹ کر دیتے ہیں، صرف فرق ادا کرنا ہوتا ہے۔',
  },
  {
    questionEn: 'Can I get a car on instalments?',
    questionUr: 'کیا گاڑی انسٹالمنٹ پر مل سکتی ہے؟',
    answerEn: 'We arrange instalment and bank financing through our partner network. Call Chaudhry Naeem Akhtar on 0315 5521697 with your budget and the car you want.',
    answerUr: 'ہم اپنے پارٹنر نیٹ ورک کے ذریعے انسٹالمنٹ اور بینک فنانس کرواتے ہیں۔ اپنا بجٹ اور پسند کی گاڑی بتا کر چوہدری نعیم اختر کو 0315 5521697 پر کال کریں۔',
  },
  {
    questionEn: 'How do I check a car before travelling to the dealership?',
    questionUr: 'پلاٹ پر آنے سے پہلے گاڑی کیسے دیکھ سکتا ہوں؟',
    answerEn: 'Open the car page on this website for photos, price and specs, then tap the WhatsApp button. We send extra photos and video of the exact car, including the meter and engine, before you visit.',
    answerUr: 'اس ویب سائٹ پر گاڑی کا صفحہ کھول کر تصاویر، قیمت اور تفصیلات دیکھیں، پھر واٹس ایپ بٹن دبائیں۔ تشریف لانے سے پہلے ہم اُسی گاڑی کی مزید تصاویر اور ویڈیو، میٹر اور انجن سمیت بھیج دیتے ہیں۔',
  },
];

/**
 * Demo inventory. Photos come from tools/photo-manifest.json, so only the
 * business data lives here.
 */
const u = (text) => text;

export const cars = [
  {
    key: 'suzuki-alto-vxr',
    titleEn: 'Suzuki Alto VXR',
    titleUr: 'سوزوکی آلٹو VXR',
    brand: 'Suzuki',
    model: 'Alto',
    variant: 'VXR',
    year: 2022,
    price: 2650000,
    mileageKm: 32000,
    fuel: 'petrol',
    transmission: 'manual',
    engineCc: 660,
    colorEn: 'White',
    colorUr: 'سفید',
    bodyType: 'hatchback',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Excellent',
    conditionUr: 'بہترین',
    status: 'available',
    featured: true,
    descriptionEn: 'First-owner Alto VXR with the original Japan-assembled finish, complete service record and only 32,000 km on the meter. Ideal first car for Islamabad — light steering, superb fuel average and easy parking.',
    descriptionUr: 'پہلی ملکیت آلٹو VXR، مکمل سروس ریکارڈ اور صرف 32,000 کلومیٹر میٹر۔ اسلام آباد کے لیے بہترین پہلی گاڑی — ہلکا اسٹیئرنگ، زبردست ایوریج اور پارکنگ میں آسان۔',
  },
  {
    key: 'suzuki-alto-vxl-ags',
    titleEn: 'Suzuki Alto VXL AGS',
    titleUr: 'سوزوکی آلٹو VXL AGS',
    brand: 'Suzuki',
    model: 'Alto',
    variant: 'VXL AGS',
    year: 2021,
    price: 2950000,
    mileageKm: 41500,
    fuel: 'petrol',
    transmission: 'automatic',
    engineCc: 660,
    colorEn: 'Silver',
    colorUr: 'سلور',
    bodyType: 'hatchback',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Excellent',
    conditionUr: 'بہترین',
    status: 'available',
    featured: false,
    descriptionEn: 'Top-of-the-line Alto VXL with the factory AGS automatic gearbox, alloy wheels, power windows and original air-conditioning. City traffic becomes effortless in this one.',
    descriptionUr: 'آلٹو VXL ٹاپ ماڈل مع فیکٹری AGS آٹومیٹک گیئر، ایلائے وہیلز، پاور ونڈوز اور بالکل ٹھیک ایئر کنڈیشنر۔ شہر کے رش میں چلانا بہت آسان۔',
  },
  {
    key: 'suzuki-mehran-vxr',
    titleEn: 'Suzuki Mehran VXR',
    titleUr: 'سوزوکی مہران VXR',
    brand: 'Suzuki',
    model: 'Mehran',
    variant: 'VXR',
    year: 2017,
    price: 1450000,
    mileageKm: 78000,
    fuel: 'petrol',
    transmission: 'manual',
    engineCc: 800,
    colorEn: 'White',
    colorUr: 'سفید',
    bodyType: 'hatchback',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Good',
    conditionUr: 'اچھی',
    status: 'available',
    featured: true,
    descriptionEn: 'The most economical car on the yard and still the easiest to maintain. Clean interior, no accident history, and parts available at every corner shop.',
    descriptionUr: 'پلاٹ کی سب سے کم خرچ اور سب سے آسان دیکھ بھال والی گاڑی۔ صاف ستھرا اندرونی حصہ، کوئی ایکسیڈنٹ نہیں، اور پرزے ہر بازار میں دستیاب۔',
  },
  {
    key: 'suzuki-cultus-vxl',
    titleEn: 'Suzuki Cultus VXL',
    titleUr: 'سوزوکی کلٹس VXL',
    brand: 'Suzuki',
    model: 'Cultus',
    variant: 'VXL',
    year: 2020,
    price: 3250000,
    mileageKm: 46000,
    fuel: 'petrol',
    transmission: 'manual',
    engineCc: 1000,
    colorEn: 'Grey',
    colorUr: 'گری',
    bodyType: 'hatchback',
    registeredCityEn: 'Rawalpindi',
    registeredCityUr: 'راولپنڈی',
    conditionEn: 'Excellent',
    conditionUr: 'بہترین',
    status: 'available',
    featured: false,
    descriptionEn: 'Second-generation Cultus with the reliable K10 engine, ABS, dual airbags and factory-fitted immobiliser. A roomy, quiet hatchback that cruises comfortably on the motorway.',
    descriptionUr: 'دوسری جنریشن کلٹس، بھروسے والا K10 انجن، ABS، دو ایئر بیگز اور فیکٹری امبولائزر۔ کشادہ اور پرسکون گاڑی، موٹروے پر بھی آرام سے چلتی ہے۔',
  },
  {
    key: 'suzuki-wagon-r-vxl',
    titleEn: 'Suzuki Wagon R VXL',
    titleUr: 'سوزوکی ویگن آر VXL',
    brand: 'Suzuki',
    model: 'Wagon R',
    variant: 'VXL',
    year: 2019,
    price: 2750000,
    mileageKm: 69000,
    fuel: 'petrol',
    transmission: 'manual',
    engineCc: 1000,
    colorEn: 'White',
    colorUr: 'سفید',
    bodyType: 'hatchback',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Good',
    conditionUr: 'اچھی',
    status: 'available',
    featured: false,
    descriptionEn: 'Tall-boy comfort with the best headroom in its class, a deep boot and 1,000 cc economy. Popular with families and ride-hailing drivers alike.',
    descriptionUr: 'لمبے قد والوں کے لیے کشادہ کیبن، کلاس میں سب سے زیادہ سر کی جگہ، گہرا بُوٹ اور 1,000 سی سی کی کفایت۔ فیملیز اور رائیڈ ہیلنگ دونوں کے لیے پسندیدہ۔',
  },
  {
    key: 'suzuki-swift-glx',
    titleEn: 'Suzuki Swift GLX',
    titleUr: 'سوزوکی سوئفٹ GLX',
    brand: 'Suzuki',
    model: 'Swift',
    variant: 'GLX CVT',
    year: 2021,
    price: 4150000,
    mileageKm: 38000,
    fuel: 'petrol',
    transmission: 'automatic',
    engineCc: 1200,
    colorEn: 'Red',
    colorUr: 'سرخ',
    bodyType: 'hatchback',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Excellent',
    conditionUr: 'بہترین',
    status: 'available',
    featured: true,
    descriptionEn: 'The 1.2 litre Swift GLX with CVT, keyless entry, push start and a punchy drive that still returns over 14 km/l in the city. Genuine low mileage and untouched paint.',
    descriptionUr: '1.2 لیٹر سوئفٹ GLX مع CVT، کی لیس انٹری، پش اسٹارٹ اور شاندار پک اپ، پھر بھی شہر میں 14 کلومیٹر فی لیٹر سے زیادہ ایوریج۔ اصلی کم میٹر اور اچھوتا پینٹ۔',
  },
  {
    key: 'suzuki-bolan-vx',
    titleEn: 'Suzuki Bolan VX',
    titleUr: 'سوزوکی بولان VX',
    brand: 'Suzuki',
    model: 'Bolan',
    variant: 'VX',
    year: 2021,
    price: 1600000,
    mileageKm: 55000,
    fuel: 'petrol',
    transmission: 'manual',
    engineCc: 800,
    colorEn: 'White',
    colorUr: 'سفید',
    bodyType: 'van',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Good',
    conditionUr: 'اچھی',
    status: 'available',
    featured: false,
    descriptionEn: 'Seven-seater Bolan VX with factory CNG option removed and petrol running only — a dependable load carrier for a small business or a large family.',
    descriptionUr: 'سات نشستوں والا بولان VX، صرف پیٹرول پر چلنے والا — چھوٹے کاروبار یا بڑے خاندان کے لیے بھروسے والا ساتھی۔',
  },
  {
    key: 'suzuki-ravi',
    titleEn: 'Suzuki Ravi',
    titleUr: 'سوزوکی راوی',
    brand: 'Suzuki',
    model: 'Ravi',
    variant: 'Standard',
    year: 2019,
    price: 1150000,
    mileageKm: 61000,
    fuel: 'petrol',
    transmission: 'manual',
    engineCc: 800,
    colorEn: 'White',
    colorUr: 'سفید',
    bodyType: 'pickup',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Good',
    conditionUr: 'اچھی',
    status: 'sold',
    featured: false,
    descriptionEn: 'A hard-working Ravi pickup with a reinforced deck, new tyres and a rebuilt carburettor. Already sold — call us and we will arrange a similar unit for you.',
    descriptionUr: 'محنت کرنے والا راوی پک اپ، مضبوط ڈیک، نئے ٹائر اور نیا کاربوریٹر۔ یہ گاڑی فروخت ہو چکی ہے — کال کریں، ہم ایسی ہی کوئی گاڑی آپ کے لیے لگوا دیں گے۔',
  },
  {
    key: 'toyota-corolla-gli',
    titleEn: 'Toyota Corolla GLi 1.3',
    titleUr: 'ٹویوٹا کرولا GLi 1.3',
    brand: 'Toyota',
    model: 'Corolla',
    variant: 'GLi 1.3 VVTi',
    year: 2019,
    price: 4350000,
    mileageKm: 54000,
    fuel: 'petrol',
    transmission: 'manual',
    engineCc: 1300,
    colorEn: 'White',
    colorUr: 'سفید',
    bodyType: 'sedan',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Excellent',
    conditionUr: 'بہترین',
    status: 'available',
    featured: true,
    descriptionEn: 'Corolla GLi with the bulletproof 1.3 VVTi engine, original paint on every panel, full Toyota service history and brand-new tyres fitted last month.',
    descriptionUr: 'کرولا GLi، ناقابلِ شکست 1.3 VVTi انجن، ہر پینل پر اصلی پینٹ، مکمل ٹویوٹا سروس ہسٹری اور پچھلے مہینے ڈالے گئے نئے ٹائر۔',
  },
  {
    key: 'toyota-corolla-altis',
    titleEn: 'Toyota Corolla Altis 1.6',
    titleUr: 'ٹویوٹا کرولا الٹس 1.6',
    brand: 'Toyota',
    model: 'Corolla',
    variant: 'Altis 1.6 CVT',
    year: 2021,
    price: 6250000,
    mileageKm: 33000,
    fuel: 'petrol',
    transmission: 'automatic',
    engineCc: 1600,
    colorEn: 'Silver',
    colorUr: 'سلور',
    bodyType: 'sedan',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Excellent',
    conditionUr: 'بہترین',
    status: 'available',
    featured: true,
    descriptionEn: 'Altis 1.6 automatic with paddle shifters, cruise control, T-Connect screen and factory 7 airbags. Under warranty history, single owner, non-accidental.',
    descriptionUr: 'الٹس 1.6 آٹومیٹک مع پیڈل شفٹرز، کروز کنٹرول، ٹی-کنیکٹ اسکرین اور فیکٹری 7 ایئر بیگز۔ ایک ہی مالک، کوئی ایکسیڈنٹ نہیں۔',
  },
  {
    key: 'toyota-yaris-ativ',
    titleEn: 'Toyota Yaris ATIV X',
    titleUr: 'ٹویوٹا یارس ATIV X',
    brand: 'Toyota',
    model: 'Yaris',
    variant: 'ATIV X 1.3 CVT',
    year: 2020,
    price: 4650000,
    mileageKm: 47000,
    fuel: 'petrol',
    transmission: 'automatic',
    engineCc: 1300,
    colorEn: 'Grey',
    colorUr: 'گری',
    bodyType: 'sedan',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Excellent',
    conditionUr: 'بہترین',
    status: 'available',
    featured: false,
    descriptionEn: 'Yaris ATIV X CVT with reverse camera, alloy wheels, climate control and push start. Smooth, light and remarkably economical for a sedan of this size.',
    descriptionUr: 'یارس ATIV X CVT مع ریورس کیمرہ، ایلائے وہیلز، کلائمیٹ کنٹرول اور پش اسٹارٹ۔ اس سائز کی سیڈان کے لیے نہایت ہموار اور کفایتی گاڑی۔',
  },
  {
    key: 'toyota-vitz-hybrid',
    titleEn: 'Toyota Vitz Hybrid',
    titleUr: 'ٹویوٹا وٹز ہائبرڈ',
    brand: 'Toyota',
    model: 'Vitz',
    variant: 'Hybrid F',
    year: 2017,
    price: 3850000,
    mileageKm: 62000,
    fuel: 'hybrid',
    transmission: 'automatic',
    engineCc: 1500,
    colorEn: 'White',
    colorUr: 'سفید',
    bodyType: 'hatchback',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Very Good',
    conditionUr: 'بہت اچھی',
    status: 'available',
    featured: false,
    descriptionEn: 'Imported Vitz hybrid with fresh auction sheet, healthy hybrid battery (checked and tested) and an average of 22 km/l in city driving.',
    descriptionUr: 'امپورٹڈ وٹز ہائبرڈ، تازہ آکشن شیٹ، مکمل چیک شدہ صحت مند ہائبرڈ بیٹری اور شہر میں 22 کلومیٹر فی لیٹر ایوریج۔',
  },
  {
    key: 'toyota-passo-x',
    titleEn: 'Toyota Passo X',
    titleUr: 'ٹویوٹا پاسو X',
    brand: 'Toyota',
    model: 'Passo',
    variant: 'X L-Package',
    year: 2016,
    price: 3150000,
    mileageKm: 74000,
    fuel: 'petrol',
    transmission: 'automatic',
    engineCc: 1000,
    colorEn: 'Maroon',
    colorUr: 'مرون',
    bodyType: 'hatchback',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Very Good',
    conditionUr: 'بہت اچھی',
    status: 'sold',
    featured: false,
    descriptionEn: 'Compact Japanese hatchback with push start, climate control and a genuinely small turning circle. Sold — a similar Passo or Vitz can be arranged on request.',
    descriptionUr: 'چھوٹی جاپانی ہیچ بیک مع پش اسٹارٹ، کلائمیٹ کنٹرول اور نہایت کم ٹرننگ سرکل۔ فروخت ہو چکی — درخواست پر ایسی ہی پاسو یا وٹز لگوائی جا سکتی ہے۔',
  },
  {
    key: 'toyota-prado-tx',
    titleEn: 'Toyota Land Cruiser Prado TX',
    titleUr: 'ٹویوٹا لینڈ کروزر پراڈو TX',
    brand: 'Toyota',
    model: 'Land Cruiser Prado',
    variant: 'TX 2.7',
    year: 2014,
    price: 21500000,
    mileageKm: 96000,
    fuel: 'petrol',
    transmission: 'automatic',
    engineCc: 2700,
    colorEn: 'Pearl White',
    colorUr: 'پرل وائٹ',
    bodyType: 'suv',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Excellent',
    conditionUr: 'بہترین',
    status: 'available',
    featured: true,
    descriptionEn: 'Full-option Prado TX with sunroof, leather, 7 seats, rear entertainment and fresh suspension work. Fully documented import — a proper Islamabad SUV.',
    descriptionUr: 'فل آپشن پراڈو TX مع سن روف، لیدر، 7 نشستیں، ریئر انٹرٹینمنٹ اور نئی سسپنشن۔ مکمل دستاویزی امپورٹ — اسلام آباد کے لیے مکمل SUV۔',
  },
  {
    key: 'toyota-hilux-revo',
    titleEn: 'Toyota Hilux Revo',
    titleUr: 'ٹویوٹا ہائی لکس ریوو',
    brand: 'Toyota',
    model: 'Hilux',
    variant: 'Revo G Double Cab',
    year: 2019,
    price: 9850000,
    mileageKm: 88000,
    fuel: 'diesel',
    transmission: 'automatic',
    engineCc: 2400,
    colorEn: 'Blue',
    colorUr: 'نیلا',
    bodyType: 'pickup',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Very Good',
    conditionUr: 'بہت اچھی',
    status: 'available',
    featured: false,
    descriptionEn: 'Revo G double cab 4x4 with a factory bed liner, tow pack and hill-start assist. Recently serviced with new engine oil, filters and brake pads.',
    descriptionUr: 'ریوو G ڈبل کیب 4x4 مع فیکٹری بیڈ لائنر، ٹو پیک اور ہل اسٹارٹ اسسٹ۔ حال ہی میں نیا انجن آئل، فلٹرز اور بریک پیڈز ڈلوائے گئے۔',
  },
  {
    key: 'toyota-fortuner-legender',
    titleEn: 'Toyota Fortuner Legender',
    titleUr: 'ٹویوٹا فارچیونر لیجنڈر',
    brand: 'Toyota',
    model: 'Fortuner',
    variant: 'Legender 2.8 4x4',
    year: 2019,
    price: 16500000,
    mileageKm: 58000,
    fuel: 'diesel',
    transmission: 'automatic',
    engineCc: 2800,
    colorEn: 'White',
    colorUr: 'سفید',
    bodyType: 'suv',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Excellent',
    conditionUr: 'بہترین',
    status: 'available',
    featured: false,
    descriptionEn: 'Legender 2.8 4x4 diesel — 7 seats, leather interior, illuminated door sills and a faultless 4x4 system. Serviced only at authorised dealers.',
    descriptionUr: 'لیجنڈر 2.8 4x4 ڈیزل — 7 نشستیں، لیدر انٹیریئر، ایل ای ڈی ڈور سِلز اور بے عیب 4x4 سسٹم۔ سروس صرف مستند ڈیلرز سے کرائی گئی۔',
  },
  {
    key: 'honda-city-1-2',
    titleEn: 'Honda City 1.2',
    titleUr: 'ہونڈا سٹی 1.2',
    brand: 'Honda',
    model: 'City',
    variant: '1.2 i-VTEC',
    year: 2020,
    price: 4950000,
    mileageKm: 42000,
    fuel: 'petrol',
    transmission: 'manual',
    engineCc: 1200,
    colorEn: 'White',
    colorUr: 'سفید',
    bodyType: 'sedan',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Excellent',
    conditionUr: 'بہترین',
    status: 'available',
    featured: true,
    descriptionEn: 'Sixth-generation City 1.2 with a spotless interior, original Honda audio, ECO mode and a boot big enough for the whole family luggage.',
    descriptionUr: 'چھٹی جنریشن سٹی 1.2، بالکل صاف اندرونی حصہ، اصلی ہونڈا آڈیو، ECO موڈ اور اتنا بڑا بُوٹ کہ پوری فیملی کا سامان آ جائے۔',
  },
  {
    key: 'honda-civic-oriel',
    titleEn: 'Honda Civic Oriel',
    titleUr: 'ہونڈا سوک Oriel',
    brand: 'Honda',
    model: 'Civic',
    variant: 'Oriel 1.5 Turbo',
    year: 2020,
    price: 8650000,
    mileageKm: 35000,
    fuel: 'petrol',
    transmission: 'automatic',
    engineCc: 1500,
    colorEn: 'Modern Steel',
    colorUr: 'ماڈرن اسٹیل',
    bodyType: 'sedan',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Excellent',
    conditionUr: 'بہترین',
    status: 'available',
    featured: true,
    descriptionEn: 'Civic Oriel 1.5 turbo with sunroof, leather, full LED headlamps and Honda Sensing safety package. First owner, complete Honda dealership history.',
    descriptionUr: 'سوک Oriel 1.5 ٹربو مع سن روف، لیدر، مکمل ایل ای ڈی ہیڈ لیمپس اور ہونڈا سینسنگ سیفٹی پیکج۔ پہلی ملکیت، مکمل ہونڈا ڈیلر ہسٹری۔',
  },
  {
    key: 'honda-br-v',
    titleEn: 'Honda BR-V',
    titleUr: 'ہونڈا BR-V',
    brand: 'Honda',
    model: 'BR-V',
    variant: 'i-VTEC S CVT',
    year: 2021,
    price: 5450000,
    mileageKm: 44000,
    fuel: 'petrol',
    transmission: 'automatic',
    engineCc: 1500,
    colorEn: 'White',
    colorUr: 'سفید',
    bodyType: 'suv',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Excellent',
    conditionUr: 'بہترین',
    status: 'available',
    featured: false,
    descriptionEn: 'Seven-seat BR-V with a genuinely usable third row, roof-mounted rear cooling vents and class-leading ground clearance for the rough patches.',
    descriptionUr: 'سات نشستوں والی BR-V، واقعی کام آنے والی تیسری قطار، چھت سے ریئر کولنگ وینٹس اور خراب سڑکوں کے لیے بہترین گراؤنڈ کلیئرنس۔',
  },
  {
    key: 'honda-vezel-hybrid',
    titleEn: 'Honda Vezel Hybrid',
    titleUr: 'ہونڈا ویزل ہائبرڈ',
    brand: 'Honda',
    model: 'Vezel',
    variant: 'Hybrid Z',
    year: 2016,
    price: 5950000,
    mileageKm: 68000,
    fuel: 'hybrid',
    transmission: 'automatic',
    engineCc: 1500,
    colorEn: 'Dark Grey',
    colorUr: 'ڈارک گری',
    bodyType: 'crossover',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Very Good',
    conditionUr: 'بہت اچھی',
    status: 'sold',
    featured: false,
    descriptionEn: 'Vezel Hybrid Z with paddle shifters, cruise control and a tested hybrid battery. This unit is sold — tell us your budget and we will source another one.',
    descriptionUr: 'ویزل ہائبرڈ Z مع پیڈل شفٹرز، کروز کنٹرول اور مکمل ٹیسٹ شدہ ہائبرڈ بیٹری۔ یہ گاڑی بک ہو چکی ہے — اپنا بجٹ بتائیں، ہم ایسی ہی دوسری لگوا دیں گے۔',
  },
  {
    key: 'kia-sportage-awd',
    titleEn: 'Kia Sportage AWD',
    titleUr: 'کیا اسپورٹیج AWD',
    brand: 'Kia',
    model: 'Sportage',
    variant: 'AWD 2.0',
    year: 2021,
    price: 8950000,
    mileageKm: 39000,
    fuel: 'petrol',
    transmission: 'automatic',
    engineCc: 2000,
    colorEn: 'Clear White',
    colorUr: 'کلئیر وائٹ',
    bodyType: 'suv',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Excellent',
    conditionUr: 'بہترین',
    status: 'available',
    featured: true,
    descriptionEn: 'All-wheel-drive Sportage with panoramic sunroof, powered tailgate, ventilated seats and a full Kia service record. A superbly quiet highway cruiser.',
    descriptionUr: 'آل وہیل ڈرائیو اسپورٹیج مع پینورامک سن روف، پاور ٹیل گیٹ، وینٹیلیٹڈ سیٹس اور مکمل کیا سروس ریکارڈ۔ موٹروے پر نہایت پرسکون اور خاموش گاڑی۔',
  },
  {
    key: 'hyundai-tucson-fwd',
    titleEn: 'Hyundai Tucson FWD',
    titleUr: 'ہنڈائی ٹکسن FWD',
    brand: 'Hyundai',
    model: 'Tucson',
    variant: 'FWD GLS Sport',
    year: 2021,
    price: 8450000,
    mileageKm: 41000,
    fuel: 'petrol',
    transmission: 'automatic',
    engineCc: 2000,
    colorEn: 'Blue',
    colorUr: 'نیلا',
    bodyType: 'suv',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Excellent',
    conditionUr: 'بہترین',
    status: 'available',
    featured: false,
    descriptionEn: 'Tucson GLS Sport with wireless charging, Apple CarPlay, 10-way powered driver seat and a faultless automatic. Within Hyundai warranty history.',
    descriptionUr: 'ٹکسن GLS Sport مع وائرلیس چارجنگ، ایپل کاپلے، 10 طریقوں سے ایڈجسٹ ہونے والی ڈرائیور سیٹ اور بے عیب آٹومیٹک گیئر۔ ہنڈائی وارنٹی ہسٹری موجود۔',
  },
  {
    key: 'mg-hs-essence',
    titleEn: 'MG HS Essence',
    titleUr: 'ایم جی HS ایسنس',
    brand: 'MG',
    model: 'HS',
    variant: 'Essence 1.5 Turbo',
    year: 2021,
    price: 7950000,
    mileageKm: 36000,
    fuel: 'petrol',
    transmission: 'automatic',
    engineCc: 1500,
    colorEn: 'White',
    colorUr: 'سفید',
    bodyType: 'suv',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Excellent',
    conditionUr: 'بہترین',
    status: 'available',
    featured: false,
    descriptionEn: 'MG HS Essence with the panoramic roof, 360-degree camera, Bose-style audio and full digital cockpit. Genuine low mileage under first ownership.',
    descriptionUr: 'ایم جی HS ایسنس مع پینورامک روف، 360 ڈگری کیمرہ، شاندار آڈیو سسٹم اور فل ڈیجیٹل ڈیش بورڈ۔ پہلی ملکیت، اصلی کم میٹر۔',
  },
  {
    key: 'daihatsu-mira-es',
    titleEn: 'Daihatsu Mira e:S',
    titleUr: 'ڈائی ہاٹسو میرا e:S',
    brand: 'Daihatsu',
    model: 'Mira',
    variant: 'e:S L',
    year: 2016,
    price: 2850000,
    mileageKm: 66000,
    fuel: 'petrol',
    transmission: 'automatic',
    engineCc: 660,
    colorEn: 'Pink',
    colorUr: 'گلابی',
    bodyType: 'hatchback',
    registeredCityEn: 'Islamabad',
    registeredCityUr: 'اسلام آباد',
    conditionEn: 'Very Good',
    conditionUr: 'بہت اچھی',
    status: 'available',
    featured: false,
    descriptionEn: 'Kei-class Mira e:S that returns up to 30 km/l — the most economical automatic on our yard, with smart key, climate control and a fresh service.',
    descriptionUr: 'کی کلاس میرا e:S جو 30 کلومیٹر فی لیٹر تک ایوریج دیتی ہے — ہمارے پلاٹ کی سب سے کفایتی آٹومیٹک گاڑی، اسمارٹ کی، کلائمیٹ کنٹرول اور تازہ سروس کے ساتھ۔',
  },
];

export const inquiryNotes = u('');
